# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(CMAKE_COMMAND) -E cmake_progress_start "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0/CMakeFiles" "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0/src/Tutorial_01/CMakeFiles/progress.marks"
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f CMakeFiles/Makefile2 src/Tutorial_01/all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f CMakeFiles/Makefile2 src/Tutorial_01/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f CMakeFiles/Makefile2 src/Tutorial_01/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f CMakeFiles/Makefile2 src/Tutorial_01/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/rule:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f CMakeFiles/Makefile2 src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/rule
.PHONY : src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/rule

# Convenience name for target.
mytest1_glfw: src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/rule

.PHONY : mytest1_glfw

# fast build rule for target.
mytest1_glfw/fast:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build
.PHONY : mytest1_glfw/fast

__/__/dep/include/glad/glad/glad.o: __/__/dep/include/glad/glad/glad.c.o

.PHONY : __/__/dep/include/glad/glad/glad.o

# target to build an object file
__/__/dep/include/glad/glad/glad.c.o:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/__/__/dep/include/glad/glad/glad.c.o
.PHONY : __/__/dep/include/glad/glad/glad.c.o

__/__/dep/include/glad/glad/glad.i: __/__/dep/include/glad/glad/glad.c.i

.PHONY : __/__/dep/include/glad/glad/glad.i

# target to preprocess a source file
__/__/dep/include/glad/glad/glad.c.i:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/__/__/dep/include/glad/glad/glad.c.i
.PHONY : __/__/dep/include/glad/glad/glad.c.i

__/__/dep/include/glad/glad/glad.s: __/__/dep/include/glad/glad/glad.c.s

.PHONY : __/__/dep/include/glad/glad/glad.s

# target to generate assembly for a file
__/__/dep/include/glad/glad/glad.c.s:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/__/__/dep/include/glad/glad/glad.c.s
.PHONY : __/__/dep/include/glad/glad/glad.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(MAKE) -f src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/build.make src/Tutorial_01/CMakeFiles/mytest1_glfw.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mytest1_glfw"
	@echo "... __/__/dep/include/glad/glad/glad.o"
	@echo "... __/__/dep/include/glad/glad/glad.i"
	@echo "... __/__/dep/include/glad/glad/glad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd "/media/jhorel/DATA/Universidad/7mo semestre/grafica/texturas0" && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

